//Generated by ubrpcgen
//This file is generated automatically from idl file
//Do not edit this file, since any modification will be lost when this
//file is regenerated
#ifndef __CHESS_HALL_PROPS_IDL_CHESSHALLPROPS_H_
#define __CHESS_HALL_PROPS_IDL_CHESSHALLPROPS_H_
#include "chess_hall_props.idl.h"
#include "ubrpc/servlet/servlet.h"
namespace idl
{
	class chesshallprops_servlet_trunk : public ubrpc::Servlet
	{
	protected:
		static const char * const ERROR_MSG [];
		/**
		 * @brief
		 * 设置出错信息，错误号为ERROR_常量，data为用户自定义字符串
		**/
		int setError(unsigned int err_no, const char * data);
		/**
		 * @brief
		 * rpc调用的参考签名。用户实现子类中必须必须重写这个函数
		**/
		virtual int obtain_commodity(const chesshallprops_obtain_commodity_params &, chesshallprops_obtain_commodity_response &) = 0;
		/**
		 * @brief
		 * rpc调用的参考签名。用户实现子类中必须必须重写这个函数
		**/
		virtual int obtain_exchange_code(const chesshallprops_obtain_exchange_code_params &, chesshallprops_obtain_exchange_code_response &) = 0;
		/**
		 * @brief
		 * rpc调用的参考签名。用户实现子类中必须必须重写这个函数
		**/
		virtual int use_exchange_code(const chesshallprops_use_exchange_code_params &, chesshallprops_use_exchange_code_response &) = 0;
		/**
		 * @brief
		 * rpc跳转表
		**/
		virtual int dispatch(int64_t id, const char * function, const mc_pack_t * param, mc_pack_t * result);
	};
}
#endif //__CHESS_HALL_PROPS_IDL_CHESSHALLPROPS_H_
