//Generated by ubrpcgen
//This file is generated automatically from idl file
//Do not edit this file, since any modification will be lost when this
//file is regenerated
#ifndef __MCP_IDL_NOTIFY_H_
#define __MCP_IDL_NOTIFY_H_
#include "mcp.idl.h"
#include "ubrpc/servlet/servlet.h"
namespace idl
{
	class Notify_servlet_trunk : public ubrpc::Servlet
	{
	protected:
		static const char * const ERROR_MSG [];
		/**
		 * @brief
		 * 设置出错信息，错误号为ERROR_常量，data为用户自定义字符串
		**/
		int setError(unsigned int err_no, const char * data);
		/**
		 * @brief
		 * rpc调用的参考签名。用户实现子类中必须必须重写这个函数
		**/
		virtual int addSystemNotify(const Notify_addSystemNotify_params &, Notify_addSystemNotify_response &) = 0;
		/**
		 * @brief
		 * rpc跳转表
		**/
		virtual int dispatch(int64_t id, const char * function, const mc_pack_t * param, mc_pack_t * result);
	};
}
#endif //__MCP_IDL_NOTIFY_H_
